var nfl2016Wk1 = [
  {date:20160808,home:nflBroncos,homeScore:21,away:nflPanthers,awayScore:20,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160911,home:nflTitans,homeScore:16,away:nflVikings,awayScore:25,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160911,home:nflTexans,homeScore:23,away:nflBears,awayScore:14,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160911,home:nflEagles,homeScore:29,away:nflBrowns,awayScore:10,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160911,home:nflRavens,homeScore:13,away:nflBills,awayScore:7,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160911,home:nflChiefs,homeScore:33,away:nflChargers,awayScore:27,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160911,home:nflSaints,homeScore:34,away:nflRaiders,awayScore:35,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160911,home:nflFalcons,homeScore:24,away:nflBuccaneers,awayScore:31,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160911,home:nflJets,homeScore:22,away:nflBengals,awayScore:23,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160911,home:nflJaguars,homeScore:23,away:nflPackers,awayScore:27,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160911,home:nflSeahawks,homeScore:12,away:nflDolphins,awayScore:10,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160911,home:nflCowboys,homeScore:19,away:nflGiants,awayScore:20,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160911,home:nflColts,homeScore:35,away:nflLions,awayScore:39,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160911,home:nflCardinals,homeScore:21,away:nflPatriots,awayScore:23,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160912,home:nflRedskins,homeScore:16,away:nflSteelers,awayScore:38,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160912,home:nflNiners,homeScore:28,away:nflRams,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk2 = [
  {date:20160915,home:nflBills,homeScore:0,away:nflJets,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160918,home:nflGiants,homeScore:0,away:nflSaints,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160918,home:nflLions,homeScore:0,away:nflTitans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160918,home:nflRedskins,homeScore:0,away:nflCowboys,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160918,home:nflTexans,homeScore:0,away:nflChiefs,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160918,home:nflPatriots,homeScore:0,away:nflDolphins,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160918,home:nflBrowns,homeScore:0,away:nflRavens,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160918,home:nflPanthers,homeScore:0,away:nflNiners,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160918,home:nflSteelers,homeScore:0,away:nflBengals,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160918,home:nflCardinals,homeScore:0,away:nflBuccaneers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160918,home:nflRams,homeScore:0,away:nflSeahawks,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160918,home:nflRaiders,homeScore:0,away:nflFalcons,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160918,home:nflChargers,homeScore:0,away:nflJaguars,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160918,home:nflBroncos,homeScore:0,away:nflColts,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160918,home:nflVikings,homeScore:0,away:nflPackers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160919,home:nflBears,homeScore:0,away:nflEagles,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk3 = [
  {date:20160922,home:nflPatriots,homeScore:0,away:nflTexans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160925,home:nflJaguars,homeScore:0,away:nflRavens,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160925,home:nflGiants,homeScore:0,away:nflRedskins,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160925,home:nflPackers,homeScore:0,away:nflLions,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160925,home:nflDolphins,homeScore:0,away:nflBrowns,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160925,home:nflPanthers,homeScore:0,away:nflVikings,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160925,home:nflBengals,homeScore:0,away:nflBroncos,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160925,home:nflBills,homeScore:0,away:nflCardinals,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160925,home:nflTitans,homeScore:0,away:nflRaiders,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160925,home:nflBuccaneers,homeScore:0,away:nflRams,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160925,home:nflSeahawks,homeScore:0,away:nflNiners,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160925,home:nflEagles,homeScore:0,away:nflSteelers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160925,home:nflChiefs,homeScore:0,away:nflJets,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160925,home:nflColts,homeScore:0,away:nflChargers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160925,home:nflCowboys,homeScore:0,away:nflBears,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20160926,home:nflSaints,homeScore:0,away:nflFalcons,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk4 = [
  {date:20160929,home:nflBengals,homeScore:0,away:nflDolphins,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161002,home:nflJaguars,homeScore:0,away:nflColts,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161002,home:nflPatriots,homeScore:0,away:nflBills,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161002,home:nflTexans,homeScore:0,away:nflTitans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161002,home:nflBears,homeScore:0,away:nflLions,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161002,home:nflFalcons,homeScore:0,away:nflPanthers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161002,home:nflJets,homeScore:0,away:nflSeahawks,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161002,home:nflRavens,homeScore:0,away:nflRaiders,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161002,home:nflRedskins,homeScore:0,away:nflBrowns,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161002,home:nflBuccaneers,homeScore:0,away:nflBroncos,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161002,home:nflCardinals,homeScore:0,away:nflRams,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161002,home:nflNiners,homeScore:0,away:nflCowboys,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161002,home:nflChargers,homeScore:0,away:nflSaints,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161002,home:nflSteelers,homeScore:0,away:nflChiefs,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161003,home:nflVikings,homeScore:0,away:nflGiants,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk5 = [
  {date:20161006,home:nflNiners,homeScore:0,away:nflCardinals,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161009,home:nflVikings,homeScore:0,away:nflTexans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161009,home:nflColts,homeScore:0,away:nflBears,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161009,home:nflSteelers,homeScore:0,away:nflJets,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161009,home:nflDolphins,homeScore:0,away:nflTitans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161009,home:nflLions,homeScore:0,away:nflEagles,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161009,home:nflBrowns,homeScore:0,away:nflPatriots,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161009,home:nflRavens,homeScore:0,away:nflRedskins,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161009,home:nflBroncos,homeScore:0,away:nflFalcons,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161009,home:nflCowboys,homeScore:0,away:nflBengals,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161009,home:nflRaiders,homeScore:0,away:nflChargers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161009,home:nflRams,homeScore:0,away:nflBills,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161009,home:nflPackers,homeScore:0,away:nflGiants,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161010,home:nflPanthers,homeScore:0,away:nflBuccaneers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk6 = [
  {date:20161013,home:nflChargers,homeScore:0,away:nflBroncos,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161016,home:nflRedskins,homeScore:0,away:nflEagles,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161016,home:nflDolphins,homeScore:0,away:nflSteelers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161016,home:nflBears,homeScore:0,away:nflJaguars,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161016,home:nflTitans,homeScore:0,away:nflBrowns,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161016,home:nflPatriots,homeScore:0,away:nflBengals,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161016,home:nflBills,homeScore:0,away:nflNiners,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161016,home:nflGiants,homeScore:0,away:nflRavens,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161016,home:nflLions,homeScore:0,away:nflRams,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161016,home:nflSaints,homeScore:0,away:nflPanthers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161016,home:nflRaiders,homeScore:0,away:nflChiefs,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161016,home:nflPackers,homeScore:0,away:nflCowboys,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161016,home:nflSeahawks,homeScore:0,away:nflFalcons,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161016,home:nflTexans,homeScore:0,away:nflColts,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161017,home:nflCardinals,homeScore:0,away:nflJets,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk7 = [
  {date:20161020,home:nflPackers,homeScore:0,away:nflBears,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161023,home:nflRams,homeScore:0,away:nflGiants,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161023,home:nflChiefs,homeScore:0,away:nflSaints,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161023,home:nflEagles,homeScore:0,away:nflVikings,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161023,home:nflTitans,homeScore:0,away:nflColts,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161023,home:nflDolphins,homeScore:0,away:nflBills,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161023,home:nflLions,homeScore:0,away:nflRedskins,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161023,home:nflBengals,homeScore:0,away:nflBrowns,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161023,home:nflJaguars,homeScore:0,away:nflRaiders,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161023,home:nflJets,homeScore:0,away:nflRavens,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161023,home:nflFalcons,homeScore:0,away:nflChargers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161023,home:nflNiners,homeScore:0,away:nflBuccaneers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161023,home:nflSteelers,homeScore:0,away:nflPatriots,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161023,home:nflCardinals,homeScore:0,away:nflSeahawks,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161024,home:nflBroncos,homeScore:0,away:nflTexans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk8 = [
  {date:20161027,home:nflTitans,homeScore:0,away:nflJaguars,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161030,home:nflBengals,homeScore:0,away:nflRedskins,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161030,home:nflFalcons,homeScore:0,away:nflPackers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161030,home:nflTexans,homeScore:0,away:nflLions,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161030,home:nflSaints,homeScore:0,away:nflSeahawks,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161030,home:nflColts,homeScore:0,away:nflChiefs,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161030,home:nflBrowns,homeScore:0,away:nflJets,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161030,home:nflBills,homeScore:0,away:nflPatriots,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161030,home:nflBuccaneers,homeScore:0,away:nflRaiders,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161030,home:nflBroncos,homeScore:0,away:nflChargers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161030,home:nflPanthers,homeScore:0,away:nflCardinals,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161030,home:nflCowboys,homeScore:0,away:nflEagles,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161031,home:nflBears,homeScore:0,away:nflVikings,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk9 = [
  {date:20161103,home:nflBuccaneers,homeScore:0,away:nflFalcons,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161106,home:nflVikings,homeScore:0,away:nflLions,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161106,home:nflRavens,homeScore:0,away:nflSteelers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161106,home:nflDolphins,homeScore:0,away:nflJets,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161106,home:nflBrowns,homeScore:0,away:nflCowboys,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161106,home:nflChiefs,homeScore:0,away:nflJaguars,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161106,home:nflGiants,homeScore:0,away:nflEagles,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161106,home:nflRams,homeScore:0,away:nflPanthers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161106,home:nflNiners,homeScore:0,away:nflSaints,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161106,home:nflChargers,homeScore:0,away:nflTitans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161106,home:nflPackers,homeScore:0,away:nflColts,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161106,home:nflRaiders,homeScore:0,away:nflBroncos,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161107,home:nflSeahawks,homeScore:0,away:nflBills,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk10 = [
  {date:20161110,home:nflRavens,homeScore:0,away:nflBrowns,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161113,home:nflPanthers,homeScore:0,away:nflChiefs,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161113,home:nflSaints,homeScore:0,away:nflBroncos,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161113,home:nflJets,homeScore:0,away:nflRams,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161113,home:nflTitans,homeScore:0,away:nflPackers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161113,home:nflEagles,homeScore:0,away:nflFalcons,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161113,home:nflRedskins,homeScore:0,away:nflVikings,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161113,home:nflJaguars,homeScore:0,away:nflTexans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161113,home:nflBuccaneers,homeScore:0,away:nflBears,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161113,home:nflChargers,homeScore:0,away:nflDolphins,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161113,home:nflCardinals,homeScore:0,away:nflNiners,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161113,home:nflSteelers,homeScore:0,away:nflCowboys,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161113,home:nflPatriots,homeScore:0,away:nflSeahawks,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161114,home:nflGiants,homeScore:0,away:nflBengals,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk11 = [
  {date:20161117,home:nflPanthers,homeScore:0,away:nflSaints,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161120,home:nflVikings,homeScore:0,away:nflCardinals,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161120,home:nflBengals,homeScore:0,away:nflBills,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161120,home:nflGiants,homeScore:0,away:nflBears,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161120,home:nflBrowns,homeScore:0,away:nflSteelers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161120,home:nflChiefs,homeScore:0,away:nflBuccaneers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161120,home:nflCowboys,homeScore:0,away:nflRavens,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161120,home:nflLions,homeScore:0,away:nflJaguars,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161120,home:nflColts,homeScore:0,away:nflTitans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161120,home:nflRams,homeScore:0,away:nflDolphins,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161120,home:nflNiners,homeScore:0,away:nflPatriots,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161120,home:nflSeahawks,homeScore:0,away:nflEagles,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161120,home:nflRedskins,homeScore:0,away:nflPackers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161121,home:nflRaiders,homeScore:0,away:nflTexans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk12 = [
  {date:20161124,home:nflLions,homeScore:0,away:nflVikings,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161124,home:nflCowboys,homeScore:0,away:nflRedskins,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161124,home:nflColts,homeScore:0,away:nflSteelers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161127,home:nflSaints,homeScore:0,away:nflRams,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161127,home:nflBears,homeScore:0,away:nflTitans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161127,home:nflFalcons,homeScore:0,away:nflCardinals,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161127,home:nflBrowns,homeScore:0,away:nflGiants,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161127,home:nflTexans,homeScore:0,away:nflChargers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161127,home:nflBills,homeScore:0,away:nflJaguars,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161127,home:nflRavens,homeScore:0,away:nflBengals,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161127,home:nflDolphins,homeScore:0,away:nflNiners,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161127,home:nflBuccaneers,homeScore:0,away:nflSeahawks,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161127,home:nflRaiders,homeScore:0,away:nflPanthers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161127,home:nflBroncos,homeScore:0,away:nflChiefs,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161127,home:nflJets,homeScore:0,away:nflPatriots,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161128,home:nflEagles,homeScore:0,away:nflPackers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk13 = [
  {date:20161201,home:nflVikings,homeScore:0,away:nflCowboys,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161204,home:nflSaints,homeScore:0,away:nflLions,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161204,home:nflPatriots,homeScore:0,away:nflRams,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161204,home:nflJaguars,homeScore:0,away:nflBroncos,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161204,home:nflBears,homeScore:0,away:nflNiners,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161204,home:nflPackers,homeScore:0,away:nflTexans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161204,home:nflFalcons,homeScore:0,away:nflChiefs,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161204,home:nflRavens,homeScore:0,away:nflDolphins,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161204,home:nflBengals,homeScore:0,away:nflEagles,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161204,home:nflRaiders,homeScore:0,away:nflBills,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161204,home:nflChargers,homeScore:0,away:nflBuccaneers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161204,home:nflSteelers,homeScore:0,away:nflGiants,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161204,home:nflCardinals,homeScore:0,away:nflRedskins,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161204,home:nflSeahawks,homeScore:0,away:nflPanthers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161205,home:nflJets,homeScore:0,away:nflColts,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk14 = [
  {date:20161208,home:nflChiefs,homeScore:0,away:nflRaiders,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161211,home:nflEagles,homeScore:0,away:nflRedskins,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161211,home:nflColts,homeScore:0,away:nflTexans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161211,home:nflBrowns,homeScore:0,away:nflBengals,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161211,home:nflTitans,homeScore:0,away:nflBroncos,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161211,home:nflBuccaneers,homeScore:0,away:nflSaints,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161211,home:nflDolphins,homeScore:0,away:nflCardinals,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161211,home:nflLions,homeScore:0,away:nflBears,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161211,home:nflBills,homeScore:0,away:nflSteelers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161211,home:nflPanthers,homeScore:0,away:nflChargers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161211,home:nflJaguars,homeScore:0,away:nflVikings,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161211,home:nflNiners,homeScore:0,away:nflJets,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161211,home:nflRams,homeScore:0,away:nflFalcons,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161211,home:nflPackers,homeScore:0,away:nflSeahawks,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161211,home:nflGiants,homeScore:0,away:nflCowboys,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161212,home:nflPatriots,homeScore:0,away:nflRavens,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk15 = [
  {date:20161215,home:nflSeahawks,homeScore:0,away:nflRams,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161217,home:nflJets,homeScore:0,away:nflDolphins,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161218,home:nflBills,homeScore:0,away:nflBrowns,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161218,home:nflCowboys,homeScore:0,away:nflBuccaneers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161218,home:nflGiants,homeScore:0,away:nflLions,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161218,home:nflRavens,homeScore:0,away:nflEagles,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161218,home:nflVikings,homeScore:0,away:nflColts,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161218,home:nflBears,homeScore:0,away:nflPackers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161218,home:nflChiefs,homeScore:0,away:nflTitans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161218,home:nflTexans,homeScore:0,away:nflJaguars,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161218,home:nflCardinals,homeScore:0,away:nflSaints,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161218,home:nflFalcons,homeScore:0,away:nflNiners,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161218,home:nflBroncos,homeScore:0,away:nflPatriots,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161218,home:nflChargers,homeScore:0,away:nflRaiders,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161218,home:nflBengals,homeScore:0,away:nflSteelers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161219,home:nflRedskins,homeScore:0,away:nflPanthers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk16 = [
  {date:20161222,home:nflEagles,homeScore:0,away:nflGiants,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161224,home:nflPanthers,homeScore:0,away:nflFalcons,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161224,home:nflSaints,homeScore:0,away:nflBuccaneers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161224,home:nflBills,homeScore:0,away:nflDolphins,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161224,home:nflBears,homeScore:0,away:nflRedskins,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161224,home:nflPatriots,homeScore:0,away:nflJets,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161224,home:nflBrowns,homeScore:0,away:nflChargers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161224,home:nflJaguars,homeScore:0,away:nflTitans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161224,home:nflPackers,homeScore:0,away:nflVikings,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161224,home:nflRaiders,homeScore:0,away:nflColts,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161224,home:nflRams,homeScore:0,away:nflNiners,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161224,home:nflSeahawks,homeScore:0,away:nflCardinals,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161224,home:nflTexans,homeScore:0,away:nflBengals,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161225,home:nflSteelers,homeScore:0,away:nflRavens,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161225,home:nflChiefs,homeScore:0,away:nflBroncos,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20161226,home:nflCowboys,homeScore:0,away:nflLions,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];

var nfl2016Wk17 = [
  {date:20170101,home:nflDolphins,homeScore:0,away:nflPatriots,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170101,home:nflColts,homeScore:0,away:nflJaguars,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170101,home:nflBuccaneers,homeScore:0,away:nflPanthers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170101,home:nflVikings,homeScore:0,away:nflBears,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170101,home:nflSteelers,homeScore:0,away:nflBrowns,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170101,home:nflFalcons,homeScore:0,away:nflSaints,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170101,home:nflJets,homeScore:0,away:nflBills,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170101,home:nflEagles,homeScore:0,away:nflCowboys,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170101,home:nflLions,homeScore:0,away:nflPackers,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170101,home:nflTitans,homeScore:0,away:nflTexans,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170101,home:nflRedskins,homeScore:0,away:nflGiants,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170101,home:nflBengals,homeScore:0,away:nflRavens,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170101,home:nflChargers,homeScore:0,away:nflChiefs,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170101,home:nflBroncos,homeScore:0,away:nflRaiders,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170101,home:nflNiners,homeScore:0,away:nflSeahawks,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170101,home:nflRams,homeScore:0,away:nflCardinals,awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
];
//Wildcard
var nfl2016Wk18 = [
  {date:20170107,home:"TBD",homeScore:0,away:"TBD",awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170107,home:"TBD",homeScore:0,away:"TBD",awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170108,home:"TBD",homeScore:0,away:"TBD",awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170108,home:"TBD",homeScore:0,away:"TBD",awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
]
//Divisional Round
var nfl2016Wk19 = [
  {date:20170114,home:"TBD",homeScore:0,away:"TBD",awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170114,home:"TBD",homeScore:0,away:"TBD",awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170115,home:"TBD",homeScore:0,away:"TBD",awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170115,home:"TBD",homeScore:0,away:"TBD",awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
]
//Conference Championships
var nfl2016Wk20 = [
  {date:20170122,home:"TBD",homeScore:0,away:"TBD",awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}},
  {date:20170122,home:"TBD",homeScore:0,away:"TBD",awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
]
//Super Bowl
var nfl2016Wk21 = [
  {date:20170205,home:"TBD",homeScore:0,away:"TBD",awayScore:0,get winner(){if(this.homeScore > this.awayScore){return this.home;}else if(this.awayScore > this.homeScore){return this.away;}else return null;},get loser(){if(this.homeScore < this.awayScore){return this.home;}else if(this.awayScore < this.homeScore){return this.away;}else return null;}}
]

var nflWeeks = [nfl2016Wk1,nfl2016Wk2,nfl2016Wk3,nfl2016Wk4,nfl2016Wk5,nfl2016Wk6,nfl2016Wk7,nfl2016Wk8,nfl2016Wk9,nfl2016Wk10,nfl2016Wk11,nfl2016Wk12,nfl2016Wk13,nfl2016Wk14,nfl2016Wk15,nfl2016Wk16,nfl2016Wk17,nfl2016Wk18,nfl2016Wk19,nfl2016Wk20,nfl2016Wk21];
